

export const CANONICAL_FOODS = [
  // ==========================================
  // INDIAN BREAKFAST & TRADITIONAL DISHES
  // ==========================================
  {
    id: 'food-idli',
    name: 'Steamed Idli (Rice & Urad Dal)',
    aliases: ['idli', 'idly', 'steamed idli', 'rice idli', 'urad idli'],
    cuisine: 'Indian',
    preparation: 'Steamed',
    brand: 'South Indian',
    servingSize: '1 medium idli (50g)',
    servingUnit: 'idli',
    servingGrams: 50,
    calories: 58,
    protein: 2.0,
    carbs: 12.0,
    fat: 0.2,
    fiber: 1.0,
    isFavorite: true
  },
  {
    id: 'food-plain-dosa',
    name: 'Plain Dosa (Crispy Crepe)',
    aliases: ['dosa', 'dosai', 'plain dosa', 'sada dosa'],
    cuisine: 'Indian',
    preparation: 'Pan Cooked',
    brand: 'South Indian',
    servingSize: '1 medium dosa (80g)',
    servingUnit: 'dosa',
    servingGrams: 80,
    calories: 135,
    protein: 3.2,
    carbs: 23.0,
    fat: 3.5,
    fiber: 1.2,
    isFavorite: true
  },
  {
    id: 'food-masala-dosa',
    name: 'Masala Dosa (with Potato Filling)',
    aliases: ['masala dosa', 'alu dosa', 'potato dosa'],
    cuisine: 'Indian',
    preparation: 'Pan Cooked',
    brand: 'South Indian',
    servingSize: '1 masala dosa (160g)',
    servingUnit: 'dosa',
    servingGrams: 160,
    calories: 250,
    protein: 5.5,
    carbs: 38.0,
    fat: 8.5,
    fiber: 2.8,
    isFavorite: true
  },
  {
    id: 'food-sambar',
    name: 'Sambar (Lentil & Vegetable Stew)',
    aliases: ['sambar', 'sambhar', 'sambaar', 'lentil sambar'],
    cuisine: 'Indian',
    preparation: 'Boiled / Stewed',
    brand: 'South Indian',
    servingSize: '1 bowl / cup (200ml)',
    servingUnit: 'bowl',
    servingGrams: 200,
    calories: 110,
    protein: 5.0,
    carbs: 17.0,
    fat: 2.5,
    fiber: 3.5,
    isFavorite: true
  },
  {
    id: 'food-poha',
    name: 'Poha (Flattened Rice with Turmeric & Peanuts)',
    aliases: ['poha', 'kanda poha', 'avalakki', 'chivda poha', 'beaten rice'],
    cuisine: 'Indian',
    preparation: 'Sauteed / Steamed',
    brand: 'Indian Breakfast',
    servingSize: '1 medium bowl (150g)',
    servingUnit: 'bowl',
    servingGrams: 150,
    calories: 210,
    protein: 4.5,
    carbs: 36.0,
    fat: 5.5,
    fiber: 2.5,
    isFavorite: true
  },
  {
    id: 'food-upma',
    name: 'Rava Upma (Semolina Savory Porridge)',
    aliases: ['upma', 'rava upma', 'sooji upma', 'uppittu'],
    cuisine: 'Indian',
    preparation: 'Cooked',
    brand: 'Indian Breakfast',
    servingSize: '1 medium bowl (150g)',
    servingUnit: 'bowl',
    servingGrams: 150,
    calories: 195,
    protein: 4.2,
    carbs: 32.0,
    fat: 5.8,
    fiber: 2.0,
    isFavorite: true
  },
  {
    id: 'food-medu-vada',
    name: 'Medu Vada (Crispy Lentil Fritter)',
    aliases: ['vada', 'medu vada', 'medhu vadai', 'urad vada'],
    cuisine: 'Indian',
    preparation: 'Deep Fried',
    brand: 'South Indian',
    servingSize: '1 piece (45g)',
    servingUnit: 'piece',
    servingGrams: 45,
    calories: 145,
    protein: 4.0,
    carbs: 13.0,
    fat: 8.5,
    fiber: 1.5,
    isFavorite: false
  },
  {
    id: 'food-uttapam',
    name: 'Onion Tomato Uttapam',
    aliases: ['uttapam', 'oothappam', 'onion uttapam', 'tomato uttapam'],
    cuisine: 'Indian',
    preparation: 'Pan Cooked',
    brand: 'South Indian',
    servingSize: '1 medium uttapam (120g)',
    servingUnit: 'piece',
    servingGrams: 120,
    calories: 190,
    protein: 4.5,
    carbs: 30.0,
    fat: 5.5,
    fiber: 2.5,
    isFavorite: false
  },
  {
    id: 'food-thepla',
    name: 'Methi Thepla (Gujarati Spiced Flatbread)',
    aliases: ['thepla', 'methi thepla', 'fenugreek thepla'],
    cuisine: 'Indian',
    preparation: 'Pan Cooked',
    brand: 'Gujarati',
    servingSize: '1 piece (40g)',
    servingUnit: 'piece',
    servingGrams: 40,
    calories: 115,
    protein: 3.0,
    carbs: 18.0,
    fat: 3.5,
    fiber: 2.0,
    isFavorite: false
  },

  // ==========================================
  // INDIAN MAINS, CURRIES, DALS & LEGUMES
  // ==========================================
  {
    id: 'food-dal-tadka',
    name: 'Yellow Dal Tadka (Toor / Moong Dal)',
    aliases: ['dal', 'daal', 'dal tadka', 'yellow dal', 'toor dal', 'moong dal', 'arhar dal'],
    cuisine: 'Indian',
    preparation: 'Boiled / Tempered',
    brand: 'Homemade',
    servingSize: '1 katori / bowl (150g)',
    servingUnit: 'bowl',
    servingGrams: 150,
    calories: 145,
    protein: 7.5,
    carbs: 20.0,
    fat: 3.8,
    fiber: 4.0,
    isFavorite: true
  },
  {
    id: 'food-dal-makhani',
    name: 'Dal Makhani (Black Lentils in Rich Gravy)',
    aliases: ['dal makhani', 'makhani dal', 'black dal', 'maa ki dal'],
    cuisine: 'Indian',
    preparation: 'Slow Cooked',
    brand: 'North Indian',
    servingSize: '1 katori / bowl (180g)',
    servingUnit: 'bowl',
    servingGrams: 180,
    calories: 260,
    protein: 9.0,
    carbs: 24.0,
    fat: 14.0,
    fiber: 5.5,
    isFavorite: false
  },
  {
    id: 'food-rajma-curry',
    name: 'Rajma Masala (Red Kidney Bean Curry)',
    aliases: ['rajma', 'rajma curry', 'rajma masala', 'kidney beans curry', 'rajma chawal'],
    cuisine: 'Indian',
    preparation: 'Boiled / Cooked',
    brand: 'North Indian',
    servingSize: '1 katori / bowl (180g)',
    servingUnit: 'bowl',
    servingGrams: 180,
    calories: 180,
    protein: 9.5,
    carbs: 26.0,
    fat: 4.0,
    fiber: 6.5,
    isFavorite: true
  },
  {
    id: 'food-chole-curry',
    name: 'Chole Masala (Spiced Chickpea Curry)',
    aliases: ['chole', 'chana masala', 'chole curry', 'kabuli chana', 'chickpea curry'],
    cuisine: 'Indian',
    preparation: 'Boiled / Cooked',
    brand: 'North Indian',
    servingSize: '1 katori / bowl (180g)',
    servingUnit: 'bowl',
    servingGrams: 180,
    calories: 220,
    protein: 10.0,
    carbs: 30.0,
    fat: 6.0,
    fiber: 7.0,
    isFavorite: true
  },
  {
    id: 'food-curd-rice',
    name: 'Curd Rice (Thayir Sadam / Dahi Chawal with Mustard Tempering)',
    aliases: ['curd rice', 'thayir sadam', 'dahi chawal', 'daddojanam', 'thayir satham'],
    cuisine: 'Indian',
    preparation: 'Mixed & Tempered',
    brand: 'South Indian',
    servingSize: '1 medium bowl (220g)',
    servingUnit: 'bowl',
    servingGrams: 220,
    calories: 240,
    protein: 6.5,
    carbs: 38.0,
    fat: 6.5,
    fiber: 1.5,
    isFavorite: true
  },
  {
    id: 'food-chicken-biryani',
    name: 'Chicken Dum Biryani (Hyderabadi Style)',
    aliases: ['chicken biryani', 'biryani', 'dum biryani', 'murgh biryani'],
    cuisine: 'Indian',
    preparation: 'Dum Cooked',
    brand: 'Indian Special',
    servingSize: '1 plate (350g)',
    servingUnit: 'plate',
    servingGrams: 350,
    calories: 490,
    protein: 28.0,
    carbs: 58.0,
    fat: 16.0,
    fiber: 3.0,
    isFavorite: true
  },
  {
    id: 'food-veg-biryani',
    name: 'Vegetable Biryani / Pulao',
    aliases: ['veg biryani', 'vegetable biryani', 'veg pulao', 'vegetable pulao'],
    cuisine: 'Indian',
    preparation: 'Dum Cooked',
    brand: 'Indian Special',
    servingSize: '1 plate (300g)',
    servingUnit: 'plate',
    servingGrams: 300,
    calories: 360,
    protein: 7.5,
    carbs: 60.0,
    fat: 10.0,
    fiber: 4.5,
    isFavorite: false
  },
  {
    id: 'food-khichdi',
    name: 'Moong Dal Khichdi (Rice & Lentil Comfort Bowl)',
    aliases: ['khichdi', 'dal khichdi', 'moong khichdi', 'khichuri'],
    cuisine: 'Indian',
    preparation: 'Pressure Cooked',
    brand: 'Homemade',
    servingSize: '1 bowl (220g)',
    servingUnit: 'bowl',
    servingGrams: 220,
    calories: 220,
    protein: 8.0,
    carbs: 40.0,
    fat: 3.0,
    fiber: 3.5,
    isFavorite: true
  },
  {
    id: 'food-palak-paneer',
    name: 'Palak Paneer (Cottage Cheese in Pureed Spinach Gravy)',
    aliases: ['palak paneer', 'spinach paneer', 'saag paneer'],
    cuisine: 'Indian',
    preparation: 'Cooked Gravy',
    brand: 'North Indian',
    servingSize: '1 bowl (180g)',
    servingUnit: 'bowl',
    servingGrams: 180,
    calories: 240,
    protein: 13.0,
    carbs: 8.0,
    fat: 17.0,
    fiber: 4.0,
    isFavorite: true
  },
  {
    id: 'food-paneer-butter-masala',
    name: 'Paneer Butter Masala / Paneer Makhani',
    aliases: ['paneer butter masala', 'paneer makhani', 'shahi paneer'],
    cuisine: 'Indian',
    preparation: 'Cooked Gravy',
    brand: 'North Indian',
    servingSize: '1 bowl (180g)',
    servingUnit: 'bowl',
    servingGrams: 180,
    calories: 320,
    protein: 12.0,
    carbs: 14.0,
    fat: 24.0,
    fiber: 2.5,
    isFavorite: false
  },
  {
    id: 'food-paneer-tikka',
    name: 'Tandoori Paneer Tikka (Grilled Spiced Cottage Cheese)',
    aliases: ['paneer tikka', 'tandoori paneer', 'grilled paneer'],
    cuisine: 'Indian',
    preparation: 'Tandoor / Grilled',
    brand: 'North Indian',
    servingSize: '1 plate / 6 cubes (150g)',
    servingUnit: 'plate',
    servingGrams: 150,
    calories: 280,
    protein: 19.0,
    carbs: 6.0,
    fat: 20.0,
    fiber: 1.5,
    isFavorite: true
  },
  {
    id: 'food-chicken-curry-indian',
    name: 'Homestyle Indian Chicken Curry',
    aliases: ['chicken curry', 'desi chicken curry', 'tariwala chicken', 'murgh curry'],
    cuisine: 'Indian',
    preparation: 'Cooked Gravy',
    brand: 'Homemade',
    servingSize: '1 bowl with pieces (200g)',
    servingUnit: 'bowl',
    servingGrams: 200,
    calories: 260,
    protein: 26.0,
    carbs: 6.0,
    fat: 14.0,
    fiber: 1.8,
    isFavorite: true
  },
  {
    id: 'food-egg-curry',
    name: 'Dhaba Egg Curry (2 Boiled Eggs in Spiced Onion-Tomato Gravy)',
    aliases: ['egg curry', 'anda curry', 'anda gravy', 'boiled egg curry'],
    cuisine: 'Indian',
    preparation: 'Cooked Gravy',
    brand: 'Homemade',
    servingSize: '1 bowl with 2 eggs (200g)',
    servingUnit: 'bowl',
    servingGrams: 200,
    calories: 240,
    protein: 15.0,
    carbs: 8.0,
    fat: 16.0,
    fiber: 1.5,
    isFavorite: true
  },
  {
    id: 'food-pav-bhaji',
    name: 'Pav Bhaji (Spiced Mashed Veggies with 2 Butter Pavs)',
    aliases: ['pav bhaji', 'bhaji pav', 'bombay pav bhaji'],
    cuisine: 'Indian',
    preparation: 'Mashed & Pan Cooked',
    brand: 'Street Food',
    servingSize: '1 plate (bhaji + 2 pavs) (280g)',
    servingUnit: 'plate',
    servingGrams: 280,
    calories: 420,
    protein: 9.0,
    carbs: 64.0,
    fat: 14.0,
    fiber: 6.0,
    isFavorite: false
  },

  // ==========================================
  // INDIAN FLATBREADS (ROTI, CHAPATI, PARATHA)
  // ==========================================
  {
    id: 'food-roti-chapati',
    name: 'Whole Wheat Roti / Chapati (Phulka, No Ghee)',
    aliases: ['roti', 'chapati', 'phulka', 'chappathi', 'rotli', 'wheat roti'],
    cuisine: 'Indian',
    preparation: 'Tawa Roasted / Puffed',
    brand: 'Homemade',
    servingSize: '1 medium roti (40g)',
    servingUnit: 'roti',
    servingGrams: 40,
    calories: 104,
    protein: 3.5,
    carbs: 21.0,
    fat: 0.6,
    fiber: 2.8,
    isFavorite: true
  },
  {
    id: 'food-roti-ghee',
    name: 'Whole Wheat Roti with Ghee',
    aliases: ['ghee roti', 'chapati with ghee', 'paratha plain'],
    cuisine: 'Indian',
    preparation: 'Tawa Roasted with Ghee',
    brand: 'Homemade',
    servingSize: '1 roti with 1/2 tsp ghee (45g)',
    servingUnit: 'roti',
    servingGrams: 45,
    calories: 130,
    protein: 3.5,
    carbs: 21.0,
    fat: 3.5,
    fiber: 2.8,
    isFavorite: true
  },
  {
    id: 'food-aloo-paratha',
    name: 'Aloo Paratha (Spiced Potato Stuffed Flatbread)',
    aliases: ['aloo paratha', 'alu paratha', 'potato paratha'],
    cuisine: 'Indian',
    preparation: 'Tawa Fried',
    brand: 'North Indian',
    servingSize: '1 medium paratha (120g)',
    servingUnit: 'paratha',
    servingGrams: 120,
    calories: 260,
    protein: 5.5,
    carbs: 42.0,
    fat: 8.0,
    fiber: 3.5,
    isFavorite: true
  },
  {
    id: 'food-paneer-paratha',
    name: 'Paneer Paratha (High Protein Cottage Cheese Flatbread)',
    aliases: ['paneer paratha', 'cottage cheese paratha'],
    cuisine: 'Indian',
    preparation: 'Tawa Fried',
    brand: 'North Indian',
    servingSize: '1 medium paratha (130g)',
    servingUnit: 'paratha',
    servingGrams: 130,
    calories: 310,
    protein: 13.5,
    carbs: 36.0,
    fat: 12.5,
    fiber: 3.2,
    isFavorite: true
  },

  // ==========================================
  // INDIAN FITNESS SNACKS, BEVERAGES & SOYA
  // ==========================================
  {
    id: 'food-soya-chunks',
    name: 'Soya Chunks / Mealmaker (Nutrela - Raw Dry Weight)',
    aliases: ['soya chunks', 'nutrela', 'soya bean chunks', 'mealmaker', 'soya granules'],
    cuisine: 'Indian',
    preparation: 'Boiled / Cooked',
    brand: 'Nutrela',
    servingSize: '50g dry weight (yields ~150g cooked)',
    servingUnit: 'g',
    servingGrams: 50,
    calories: 172,
    protein: 26.0,
    carbs: 16.5,
    fat: 0.3,
    fiber: 6.5,
    isFavorite: true
  },
  {
    id: 'food-moong-sprouts',
    name: 'Fresh Moong Bean Sprouts Salad',
    aliases: ['sprouts', 'moong sprouts', 'green gram sprouts', 'sprouted moong'],
    cuisine: 'Indian',
    preparation: 'Raw / Steamed',
    brand: 'Fresh Produce',
    servingSize: '1 cup (100g)',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 30,
    protein: 3.1,
    carbs: 5.9,
    fat: 0.2,
    fiber: 2.0,
    isFavorite: true
  },
  {
    id: 'food-boiled-kala-chana',
    name: 'Boiled Kala Chana (Brown / Black Chickpeas)',
    aliases: ['kala chana', 'black chana', 'desi chana', 'boiled chana'],
    cuisine: 'Indian',
    preparation: 'Boiled',
    brand: 'Homemade',
    servingSize: '1 cup cooked (150g)',
    servingUnit: 'cup',
    servingGrams: 150,
    calories: 185,
    protein: 11.0,
    carbs: 28.0,
    fat: 2.8,
    fiber: 8.5,
    isFavorite: true
  },
  {
    id: 'food-roasted-chana',
    name: 'Roasted Chana / Bhuna Chana (With Husk)',
    aliases: ['bhuna chana', 'roasted chana', 'roasted gram', 'futana'],
    cuisine: 'Indian',
    preparation: 'Dry Roasted',
    brand: 'Snack',
    servingSize: '1 handful / cup (50g)',
    servingUnit: 'g',
    servingGrams: 50,
    calories: 180,
    protein: 9.5,
    carbs: 27.0,
    fat: 2.5,
    fiber: 5.5,
    isFavorite: true
  },
  {
    id: 'food-makhana',
    name: 'Roasted Makhana (Foxnuts / Lotus Seeds in Ghee)',
    aliases: ['makhana', 'foxnuts', 'lotus seeds', 'roasted makhana', 'phool makhana'],
    cuisine: 'Indian',
    preparation: 'Dry Roasted',
    brand: 'Snack',
    servingSize: '1 large bowl (35g)',
    servingUnit: 'bowl',
    servingGrams: 35,
    calories: 130,
    protein: 3.5,
    carbs: 24.0,
    fat: 1.8,
    fiber: 2.5,
    isFavorite: true
  },
  {
    id: 'food-indian-curd',
    name: 'Fresh Homemade Dahi / Curd (Whole Milk)',
    aliases: ['curd', 'dahi', 'plain curd', 'homemade dahi', 'thayir', 'perugu'],
    cuisine: 'Indian',
    preparation: 'Fermented',
    brand: 'Dairy',
    servingSize: '1 katori / cup (150g)',
    servingUnit: 'cup',
    servingGrams: 150,
    calories: 95,
    protein: 5.2,
    carbs: 6.8,
    fat: 5.0,
    fiber: 0,
    isFavorite: true
  },
  {
    id: 'food-chaas-buttermilk',
    name: 'Chaas / Spiced Buttermilk (Masala Chaas / Mattha)',
    aliases: ['chaas', 'buttermilk', 'masala chaas', 'mattha', 'moru', 'majjiga'],
    cuisine: 'Indian',
    preparation: 'Blended',
    brand: 'Beverage',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 45,
    protein: 3.0,
    carbs: 4.5,
    fat: 1.2,
    fiber: 0.2,
    isFavorite: true
  },
  {
    id: 'food-sweet-lassi',
    name: 'Sweet Lassi (Punjabi Sweetened Yogurt Drink)',
    aliases: ['lassi', 'sweet lassi', 'punjabi lassi', 'dahi lassi'],
    cuisine: 'Indian',
    preparation: 'Blended',
    brand: 'Beverage',
    servingSize: '1 glass (300ml)',
    servingUnit: 'glass',
    servingGrams: 300,
    calories: 220,
    protein: 6.5,
    carbs: 32.0,
    fat: 7.5,
    fiber: 0,
    isFavorite: false
  },
  {
    id: 'food-paneer-raw',
    name: 'Fresh Malai Paneer / Cottage Cheese',
    aliases: ['paneer', 'cottage cheese', 'fresh paneer', 'raw paneer'],
    cuisine: 'Indian',
    preparation: 'Fresh / Raw',
    brand: 'Dairy',
    servingSize: '100g raw',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 265,
    protein: 18.0,
    carbs: 3.5,
    fat: 20.0,
    fiber: 0,
    isFavorite: true
  },
  {
    id: 'food-lowfat-paneer',
    name: 'Low-Fat High Protein Paneer',
    aliases: ['low fat paneer', 'skimmed paneer', 'diet paneer'],
    cuisine: 'Indian',
    preparation: 'Fresh / Raw',
    brand: 'Dairy',
    servingSize: '100g',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 160,
    protein: 25.0,
    carbs: 4.0,
    fat: 5.0,
    fiber: 0,
    isFavorite: true
  },

  // ==========================================
  // GLOBAL & FITNESS STAPLE PROTEINS
  // ==========================================
  {
    id: 'food-whole-egg',
    name: 'Large Whole Egg (Boiled / Poached / Fried)',
    aliases: ['egg', 'boiled egg', 'whole egg', 'fried egg', 'poached egg', 'anda'],
    cuisine: 'Global',
    preparation: 'Boiled',
    servingSize: '1 large egg (50g)',
    servingUnit: 'egg',
    servingGrams: 50,
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    fiber: 0,
    sodium: 70,
    isFavorite: true
  },
  {
    id: 'food-egg-whites',
    name: 'Egg Whites (Liquid or Boiled Whites)',
    aliases: ['egg whites', 'boiled egg white', 'egg white', 'anda safedi'],
    cuisine: 'Global',
    preparation: 'Boiled',
    servingSize: '100g (approx 3 egg whites)',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    isFavorite: true
  },
  {
    id: 'food-chicken-breast',
    name: 'Grilled Skinless Chicken Breast',
    aliases: ['chicken breast', 'grilled chicken', 'boiled chicken breast', 'cooked chicken breast'],
    cuisine: 'Global',
    preparation: 'Grilled / Baked',
    servingSize: '100g cooked',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 165,
    protein: 31.0,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    isFavorite: true
  },
  {
    id: 'food-whey-protein',
    name: 'Whey Protein Isolate / Concentrate Powder',
    aliases: ['whey', 'whey protein', 'protein powder', 'protein shake', 'whey scoop', 'isolate'],
    cuisine: 'Fitness',
    preparation: 'Powder / Shake',
    brand: 'Optimum Nutrition / MuscleBlaze',
    servingSize: '1 scoop (30g)',
    servingUnit: 'scoop',
    servingGrams: 30,
    calories: 120,
    protein: 24.0,
    carbs: 1.5,
    fat: 1.0,
    fiber: 0,
    sugar: 1.0,
    isFavorite: true
  },
  {
    id: 'food-salmon-fillet',
    name: 'Atlantic Salmon Fillet (Baked / Pan-Seared)',
    aliases: ['salmon', 'baked salmon', 'salmon fish', 'grilled salmon'],
    cuisine: 'Western',
    preparation: 'Baked / Pan Seared',
    servingSize: '150g fillet',
    servingUnit: 'g',
    servingGrams: 150,
    calories: 310,
    protein: 34.0,
    carbs: 0,
    fat: 18.0,
    sodium: 90,
    isFavorite: true
  },
  {
    id: 'food-tuna-can',
    name: 'Chunk Light Tuna in Water (Canned)',
    aliases: ['tuna', 'canned tuna', 'tuna in water', 'tuna fish'],
    cuisine: 'Global',
    preparation: 'Canned',
    servingSize: '1 can drained (140g)',
    servingUnit: 'can',
    servingGrams: 140,
    calories: 130,
    protein: 29.0,
    carbs: 0,
    fat: 1.0,
    isFavorite: false
  },
  {
    id: 'food-greek-yogurt',
    name: 'Non-Fat Plain Greek Yogurt (0% Fat)',
    aliases: ['greek yogurt', 'plain greek yogurt', 'fage', 'chobani', 'epigamia greek yogurt'],
    cuisine: 'Mediterranean',
    preparation: 'Cultured Dairy',
    brand: 'Epigamia / Fage',
    servingSize: '1 cup / container (170g)',
    servingUnit: 'g',
    servingGrams: 170,
    calories: 100,
    protein: 18.0,
    carbs: 6.0,
    fat: 0,
    fiber: 0,
    isFavorite: true
  },
  {
    id: 'food-tofu-firm',
    name: 'Organic Extra Firm Tofu',
    aliases: ['tofu', 'firm tofu', 'soy paneer', 'bean curd'],
    cuisine: 'Asian',
    preparation: 'Pan Cooked / Raw',
    brand: 'Plant-Based',
    servingSize: '100g',
    servingUnit: 'g',
    servingGrams: 100,
    calories: 83,
    protein: 10.0,
    carbs: 2.0,
    fat: 5.0,
    fiber: 1.0,
    isFavorite: false
  },

  // ==========================================
  // MILKS & BEVERAGES
  // ==========================================
  {
    id: 'food-whole-milk',
    name: 'Whole Milk (Cow / Buffalo - Full Cream)',
    aliases: ['milk', 'whole milk', 'full cream milk', 'cow milk', 'buffalo milk', 'doodh'],
    cuisine: 'Global',
    preparation: 'Pasteurized',
    brand: 'Amul / Dairy',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 150,
    protein: 8.0,
    carbs: 12.0,
    fat: 8.0,
    fiber: 0,
    sugar: 12.0,
    isFavorite: true
  },
  {
    id: 'food-skim-milk',
    name: 'Low-Fat / Toned / Skimmed Milk',
    aliases: ['skimmed milk', 'skim milk', 'toned milk', 'double toned milk', 'low fat milk'],
    cuisine: 'Global',
    preparation: 'Pasteurized',
    brand: 'Amul / Dairy',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 90,
    protein: 8.5,
    carbs: 12.5,
    fat: 0.5,
    fiber: 0,
    sugar: 12.5,
    isFavorite: true
  },
  {
    id: 'food-almond-milk',
    name: 'Unsweetened Almond Milk',
    aliases: ['almond milk', 'unsweetened almond milk'],
    cuisine: 'Plant-Based',
    preparation: 'Filtered',
    brand: 'Silk / So Good',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 40,
    protein: 1.5,
    carbs: 1.5,
    fat: 3.0,
    fiber: 0.5,
    isFavorite: false
  },
  {
    id: 'food-oat-milk',
    name: 'Oat Milk (Barista / Plain)',
    aliases: ['oat milk', 'oatmilk'],
    cuisine: 'Plant-Based',
    preparation: 'Filtered',
    brand: 'Oatly / Plant-Based',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 120,
    protein: 3.0,
    carbs: 16.0,
    fat: 5.0,
    fiber: 2.0,
    isFavorite: false
  },
  {
    id: 'food-soy-milk',
    name: 'Unsweetened Soy Milk',
    aliases: ['soy milk', 'soya milk'],
    cuisine: 'Plant-Based',
    preparation: 'Filtered',
    brand: 'Sofit / Plant-Based',
    servingSize: '1 glass (250ml)',
    servingUnit: 'glass',
    servingGrams: 250,
    calories: 100,
    protein: 7.0,
    carbs: 4.0,
    fat: 4.0,
    fiber: 1.5,
    isFavorite: false
  },

  // ==========================================
  // CARBS, GRAINS & BREADS
  // ==========================================
  {
    id: 'food-rolled-oats',
    name: 'Rolled Oats (Raw Whole Grain)',
    aliases: ['oats', 'rolled oats', 'oatmeal', 'quaker oats', 'dry oats'],
    cuisine: 'Global',
    preparation: 'Boiled / Raw',
    brand: 'Quaker / MuscleBlaze',
    servingSize: '50g dry (yields 1 cup cooked)',
    servingUnit: 'g',
    servingGrams: 50,
    calories: 190,
    protein: 6.5,
    carbs: 34.0,
    fat: 3.0,
    fiber: 5.0,
    isFavorite: true
  },
  {
    id: 'food-jasmine-rice',
    name: 'Steamed White Rice (Basmati / Sona Masoori)',
    aliases: ['white rice', 'rice', 'basmati rice', 'cooked rice', 'chawal', 'plain rice', 'boiled rice'],
    cuisine: 'Global',
    preparation: 'Steamed / Boiled',
    brand: 'Homemade',
    servingSize: '1 cup cooked (150g)',
    servingUnit: 'g',
    servingGrams: 150,
    calories: 195,
    protein: 4.2,
    carbs: 43.0,
    fat: 0.4,
    fiber: 0.6,
    isFavorite: true
  },
  {
    id: 'food-brown-rice',
    name: 'Brown Basmati Rice (Cooked)',
    aliases: ['brown rice', 'cooked brown rice', 'brown chawal'],
    cuisine: 'Global',
    preparation: 'Steamed / Boiled',
    brand: 'Homemade',
    servingSize: '1 cup cooked (150g)',
    servingUnit: 'g',
    servingGrams: 150,
    calories: 180,
    protein: 4.5,
    carbs: 38.0,
    fat: 1.5,
    fiber: 3.0,
    isFavorite: false
  },
  {
    id: 'food-brown-bread',
    name: 'Whole Wheat / Brown Bread',
    aliases: ['brown bread', 'whole wheat bread', 'wheat bread', 'brown toast'],
    cuisine: 'Western',
    preparation: 'Baked',
    brand: 'Bakery',
    servingSize: '2 slices (60g)',
    servingUnit: 'slices',
    servingGrams: 60,
    calories: 160,
    protein: 7.0,
    carbs: 28.0,
    fat: 2.0,
    fiber: 3.6,
    isFavorite: true
  },
  {
    id: 'food-white-bread',
    name: 'White Bread / White Toast',
    aliases: ['white bread', 'toast', 'bread slice', 'white toast'],
    cuisine: 'Western',
    preparation: 'Baked',
    brand: 'Bakery',
    servingSize: '2 slices (60g)',
    servingUnit: 'slices',
    servingGrams: 60,
    calories: 150,
    protein: 5.0,
    carbs: 30.0,
    fat: 1.5,
    fiber: 1.5,
    isFavorite: false
  },
  {
    id: 'food-sweet-potato',
    name: 'Boiled / Baked Sweet Potato (Shakarkandi)',
    aliases: ['sweet potato', 'boiled sweet potato', 'shakarkandi'],
    cuisine: 'Global',
    preparation: 'Boiled / Baked',
    servingSize: '150g cooked',
    servingUnit: 'g',
    servingGrams: 150,
    calories: 135,
    protein: 2.3,
    carbs: 31.0,
    fat: 0.2,
    fiber: 4.5,
    isFavorite: true
  },

  // ==========================================
  // FRUITS, NUTS & HEALTHY FATS
  // ==========================================
  {
    id: 'food-banana',
    name: 'Fresh Banana (Medium)',
    aliases: ['banana', 'ripe banana', 'kela'],
    cuisine: 'Global',
    preparation: 'Raw',
    servingSize: '1 medium banana (118g)',
    servingUnit: 'banana',
    servingGrams: 118,
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    isFavorite: true
  },
  {
    id: 'food-apple',
    name: 'Red Gala / Fuji Apple',
    aliases: ['apple', 'red apple', 'seb'],
    cuisine: 'Global',
    preparation: 'Raw',
    servingSize: '1 medium apple (182g)',
    servingUnit: 'apple',
    servingGrams: 182,
    calories: 95,
    protein: 0.5,
    carbs: 25.0,
    fat: 0.3,
    fiber: 4.4,
    isFavorite: false
  },
  {
    id: 'food-peanut-butter',
    name: 'Natural Creamy Peanut Butter (100% Peanuts)',
    aliases: ['peanut butter', 'pb', 'creamy peanut butter', 'natural peanut butter', 'pintola'],
    cuisine: 'Global',
    preparation: 'Spread',
    brand: 'Pintola / MyFitness',
    servingSize: '2 tbsp (32g)',
    servingUnit: 'tbsp',
    servingGrams: 32,
    calories: 190,
    protein: 8.0,
    carbs: 7.0,
    fat: 16.0,
    fiber: 2.0,
    isFavorite: true
  },
  {
    id: 'food-almonds',
    name: 'Raw California Almonds (Badam)',
    aliases: ['almonds', 'almond', 'badam', 'raw almonds'],
    cuisine: 'Global',
    preparation: 'Raw',
    servingSize: '1 handful / 23 nuts (28g)',
    servingUnit: 'g',
    servingGrams: 28,
    calories: 164,
    protein: 6.0,
    carbs: 6.0,
    fat: 14.0,
    fiber: 3.5,
    isFavorite: true
  },
  {
    id: 'food-avocado',
    name: 'Fresh Hass Avocado',
    aliases: ['avocado', 'butter fruit', 'hass avocado'],
    cuisine: 'Global',
    preparation: 'Raw',
    servingSize: '1/2 medium avocado (100g)',
    servingUnit: 'half',
    servingGrams: 100,
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    isFavorite: false
  },
  {
    id: 'food-blueberries',
    name: 'Fresh Blueberries',
    aliases: ['blueberries', 'blueberry', 'berries'],
    cuisine: 'Global',
    preparation: 'Raw',
    servingSize: '1 cup (148g)',
    servingUnit: 'cup',
    servingGrams: 148,
    calories: 84,
    protein: 1.1,
    carbs: 21.0,
    fat: 0.5,
    fiber: 3.6,
    isFavorite: false
  },

  // ==========================================
  // VEGETABLES
  // ==========================================
  {
    id: 'food-broccoli',
    name: 'Steamed Fresh Broccoli',
    aliases: ['broccoli', 'steamed broccoli', 'fresh broccoli'],
    cuisine: 'Global',
    preparation: 'Steamed',
    servingSize: '1 cup florets (91g)',
    servingUnit: 'g',
    servingGrams: 91,
    calories: 31,
    protein: 2.6,
    carbs: 6.0,
    fat: 0.3,
    fiber: 2.4,
    isFavorite: true
  },
  {
    id: 'food-spinach',
    name: 'Baby Spinach (Raw / Steamed Palak)',
    aliases: ['spinach', 'baby spinach', 'palak', 'steamed spinach'],
    cuisine: 'Global',
    preparation: 'Raw / Steamed',
    servingSize: '2 cups (60g)',
    servingUnit: 'g',
    servingGrams: 60,
    calories: 14,
    protein: 1.7,
    carbs: 2.2,
    fat: 0.2,
    fiber: 1.3,
    isFavorite: false
  }
];

export const SEED_FOODS = CANONICAL_FOODS;
